name: Backend Tests + Push

on:
    push:
        branches:
        - master
        paths:
        - src/github.com/eliudarudo/consuming-backend/**    

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
          - name: Set up Go 1.12
            uses: actions/setup-go@v1
            with: 
              go-version: 1.12

          - name: Check out source code
            uses: actions/checkout@master
            
          - name: Build
            env:   
              GOPROXY: "https://proxy.golang.org"
            working-directory: src/github.com/eliudarudo/consuming-backend
            run: go build .  
        
          - name: Test
            env:
              GOPROXY: "https://proxy.golang.org"
            working-directory: src/github.com/eliudarudo/consuming-backend
            run: go test ./... -cover


    cd: 
      runs-on: ubuntu-latest
      needs: ci
      env: 
        IMAGE_TAG: go-events-communication-consuming-backend
      
      steps:
          - uses: actions/checkout@master
          - name: Docker login
            run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          - name: Build
            working-directory: ./src/github.com/eliudarudo/consuming-backend
            run: docker build -t ${{ env.IMAGE_TAG }} .  
          - name: Tags  
            run: |
              docker tag ${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_TAG }}:${{ github.sha }}
              docker tag ${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_TAG }}:latest
          - name: Push
            run: |
              docker push ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_TAG }}:${{ github.sha }}
              docker push ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_TAG }}:latest
        

            