name: Frontend Tests + Push

on:
    push:
        branches:
        - master
        paths:
        - src/github.com/eliudarudo/consuming-frontend/**    

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-go@v1
            - name: Set up GOPATH
              run: go env -w GOPATH=.
            - name: Run tests
              working-directory: ./src/github.com/eliudarudo/consuming-frontend
              run: go test -v ./...  
        

            