name: Frontend Tests + Push

on:
    push:
        branches:
        - master
        paths:
        - src/github.com/eliudarudo/consuming-frontend/**    

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-go@v1
            - name: Change directory
              working-directory: ./src/github.com/eliudarudo/consuming-frontend
              run: go test -v ./...  
              env:
                CI: true
        

            